// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9N_uilXv-pGhJhdlN-KecGESUW1H-Aw',
    appId: '1:332049652543:web:7572c40dc7a93c49fed18a',
    messagingSenderId: '332049652543',
    projectId: 'chatrooms-app-a4326',
    authDomain: 'chatrooms-app-a4326.firebaseapp.com',
    storageBucket: 'chatrooms-app-a4326.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOixYZxSNuqYl8aDAMiWXKnnP0EQw9CoA',
    appId: '1:332049652543:android:61ccb1f4bf20f09cfed18a',
    messagingSenderId: '332049652543',
    projectId: 'chatrooms-app-a4326',
    storageBucket: 'chatrooms-app-a4326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGXwiz0wIdLt50590AzXiwEEgytwpKEQ',
    appId: '1:332049652543:ios:84e7152ead62adadfed18a',
    messagingSenderId: '332049652543',
    projectId: 'chatrooms-app-a4326',
    storageBucket: 'chatrooms-app-a4326.appspot.com',
    iosClientId: '332049652543-uaiv79s626rcvirbujgokcu1p4kbi0f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatroomsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLGXwiz0wIdLt50590AzXiwEEgytwpKEQ',
    appId: '1:332049652543:ios:84e7152ead62adadfed18a',
    messagingSenderId: '332049652543',
    projectId: 'chatrooms-app-a4326',
    storageBucket: 'chatrooms-app-a4326.appspot.com',
    iosClientId: '332049652543-uaiv79s626rcvirbujgokcu1p4kbi0f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatroomsApp',
  );
}
